Update the debian package build by cleaning pre and post scripts to be ran with the dash shell and by taking into account the postgresql access definition in the pg_hba.conf file. The silverpeas and openoffice init scripts are also updated

diff --git a/deb/debian/silverpeas.init b/deb/debian/silverpeas.init
--- a/deb/debian/silverpeas.init
+++ b/deb/debian/silverpeas.init
@@ -22,14 +22,15 @@ RUN_AS_USER=silverpeas
 . /lib/lsb/init-functions
 
 get_pid() {
+  PID=
+  pj=`pidof java`
+  test $? -eq 0 || return 1
   f=1
-  PID=`ps ax | grep -i jboss | tr -s ' ' | cut -d ' ' -f $f | head -n 1`
+  PID=`ps ax | grep $pj | grep silverpeas | tr -s ' ' | cut -d ' ' -f $f`
   if [ "Z$PID" = "Z" ]; then
     f=2
-    PID=`ps ax | grep -i jboss | tr -s ' ' | cut -d ' ' -f $f | head -n 1`
+    PID=`ps ax | grep $pj | grep silverpeas | tr -s ' ' | cut -d ' ' -f $f`
   fi
-  p=`ps ax | grep -i jboss | tr -s ' ' | cut -d ' ' -f $f | head -n 1`
-  test $PID -eq $p || PID=""
 }
 
 check_running()
@@ -57,9 +58,12 @@ case $1 in
     sudo -E -u $RUN_AS_USER $SILVERPEAS_HOME/bin/$PRG_START >& /var/log/silverpeas.log
     sleep 5s
     get_pid
-    echo $PID > $PIDFILE
-    [ "Z$PID" != "Z" ]
-    log_end_msg $?
+    if [ "Z$PID" != "Z" ]; then
+      echo $PID > $PIDFILE
+      log_success_msg "Started in background (can take several minutes)"
+    else
+      log_failure_msg
+    fi
     ;;
   stop)
     log_daemon_msg "Stopping $NAME"
diff --git a/deb/debian/silverpeas.postinst b/deb/debian/silverpeas.postinst
--- a/deb/debian/silverpeas.postinst
+++ b/deb/debian/silverpeas.postinst
@@ -1,21 +1,42 @@
 #!/bin/sh
 
-set -e
-
 case "$1" in
     configure)
         if ! id silverpeas > /dev/null 2>&1 ; then
-            adduser --system --home /opt/silverpeas --no-create-home \
-                --ingroup adm --disabled-password --shell /bin/bash \
-                silverpeas
+            useradd -d /opt/silverpeas -r -s /bin/bash silverpeas
+            hba_path=`find /etc/postgresql -name pg_hba.conf`
+            grep "^host[ \t]*all[ \t]*all[ \t]*127.0.0.1\/32[ \t]*ident\|^host[ \t]*all[ \t]*all[ \t]*127.0.0.1/32[ \t]*trust" $hba_path > /dev/null
+            if [ $? -eq 0 ]; then
+                # remove the permission for all with an ident or a trust credential
+                sed "s/^host[ \t]*all[ \t]*all[ \t]*[(127.0.0.1\/32)(::1\/128)]*[ \t]*[(ident)(trust)]*//" $hba_path > /tmp/pg_hba.conf
+                sudo -u postgres cp /tmp/pg_hba.conf $hba_path
+                rm -f /tmp/pg_hba.conf > /dev/null 2>&1 || true
+            fi
+            # add connection permission for the user silverpeas
+            cat >> $hba_path << EOF
+host    silverpeas             silverpeas             127.0.0.1/32            md5
+host    silverpeas             silverpeas             ::1/128                 md5
+EOF
+            chown postgres:postgres $hba_path
+            service postgresql restart
+
             SILVER_PWD=`echo $RANDOM | sha1sum | sed "s| -||g" | tr -d " "`
             echo "CREATE USER silverpeas WITH PASSWORD :silver_pwd; CREATE DATABASE silverpeas; GRANT ALL PRIVILEGES ON DATABASE silverpeas TO silverpeas;"  | sudo -u postgres psql -l -v silver_pwd="'$SILVER_PWD'" -f - 
             sed "s/@@silver_pwd@@/$SILVER_PWD/g" /opt/silverpeas/setup/settings/defaultConfig.properties > /opt/silverpeas/setup/settings/config.properties
-            echo "/opt/silverpeas/setup/settings/config.properties generated"
+            if [ -e /opt/silverpeas/setup/settings/config.properties ]; then
+                echo "config.properties generated"
+            else
+                echo "Error while generating config.properties!"
+                exit 1
+            fi
+            chown silverpeas:silverpeas /opt/silverpeas/setup/settings/config.properties
         fi
+
+        service postgresql status > /dev/null 2>&1
+        test $? -eq 0 || service postgresql start
         rm /opt/silverpeas/setup/settings/defaultConfig.properties
-        chown -R silverpeas:adm /opt/silverpeas
-        chown -R silverpeas:adm /var/data/silverpeas
+        chown -R silverpeas:silverpeas /opt/silverpeas
+        chown -R silverpeas:silverpeas /var/data/silverpeas
         . /etc/profile.d/jboss.sh
         . /etc/profile.d/silverpeas.sh
         sudo -E -u silverpeas /opt/silverpeas/bin/SilverpeasSettings.sh
